FROM golang:1.21-bullseye

RUN dpkg --add-architecture armhf

RUN apt-get update && apt-get install -y \
    gcc-arm-linux-gnueabihf \
    libsdl2-dev:armhf \
    libsdl2-mixer-dev:armhf \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build
